# -*- coding: utf-8 -*-
"""
/***************************************************************************
 LivingSOCLocator
                                 A QGIS plugin
 KoALA
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2019-08-15
        copyright            : (C) 2019 by Ansup
        email                : ansup0402@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Ansup'
__date__ = '2019-08-15'
__copyright__ = '(C) 2019 by Ansup'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load LivingSOCLocator class from file LivingSOCLocator.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .soc_locator import LivingSOCLocatorPlugin
    return LivingSOCLocatorPlugin()
